### ISSUE TITLE
Cannot find module 'C:\...\node_modules\@sentry\profiling-node\binaries\sentry_cpu_profiler-v83-win32-x64.node'

### ISSUE THREAD

**Issue by sherryysj** [getsentry/profiling-node#105]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

0.1.0

### What environment is your node script running in?

Windows

### How is your code deployed and bundled?

N/A

### Steps to Reproduce

1. run `npm i` on windows machine

### Expected Result

Package install successfully.

### Actual Result

I receive this error when installing the package.

**Comment by sherryysj** [comment]
It's fixed by installing `Visual Studio` with `Desktop development with C++` workload. However, it will be better if this can be fix in other way, since I actually do not use VS at all and it takes 17GB memory on my computer.

**Comment by JonasBa** [comment]
@sherryysj thanks for reaching out, I did not realize that is required. If this becomes a common ask, I think we should precompile the bindings for your. The reason why we haven't precompiled win32 bindings for node14 was due to their size

**Comment by sherryysj** [comment]
Thanks Jonas!

**Comment by JonasBa** [comment]
@sherryysj I'll make sure I add an entry to our readme about how to deal with this, thank you for opening the issue!
