### ISSUE TITLE
Docker build fails when installing profiling package

### ISSUE THREAD

**Issue by Himiath** [getsentry/profiling-node#132]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

0.3.0

### What environment is your node script running in?

Node/Express, fails when building docker container.

### How is your code deployed and bundled?

Building container using following dockerfile. 

```FROM node:16.13.0-alpine as builder
WORKDIR /app
COPY package.json yarn.lock /app/
RUN yarn install --frozen-lockfile
COPY . /app
RUN npm run build:ts

FROM node:16.13.0-alpine
WORKDIR /app
COPY package.json yarn.lock /app/
RUN yarn install --frozen-lockfile
COPY --from=builder /app/.uploads /app/.uploads
COPY --from=builder /app/migrations /app/migrations
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/assets /app/dist/assets
CMD node dist/src/server.js
EXPOSE 3000
```

### Steps to Reproduce

1. Add profiling to project according to docs.
2. Initiate build with dockerfile above
3. See it fail with below error.

### Expected Result

Build completes with no errors related to sentry.

### Actual Result

```
#8 92.22 error /app/node_modules/@sentry/profiling-node: Command failed.
#8 92.22 Exit code: 1
#8 92.22 Command: node scripts/check-build.js
#8 92.22 Arguments:
#8 92.22 Directory: /app/node_modules/@sentry/profiling-node
#8 92.22 Output:
#8 92.22 @sentry/profiling-node: Precompiled binary found, attempting to load...
#8 92.22 /app/node_modules/@sentry/profiling-node/scripts/check-build.js:51
#8 92.22   throw e;
#8 92.22   ^
#8 92.22
#8 92.22 Error: Error relocating /app/node_modules/@sentry/profiling-node/binaries/sentry_cpu_profiler-v93-linux-x64-musl.node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
#8 92.22     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
#8 92.22     at Module.load (node:internal/modules/cjs/loader:981:32)
#8 92.22     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
#8 92.22     at Module.require (node:internal/modules/cjs/loader:1005:19)
#8 92.22     at require (node:internal/modules/cjs/helpers:102:18)
#8 92.22     at Object.<anonymous> (/app/node_modules/@sentry/profiling-node/scripts/check-build.js:24:3)
#8 92.22     at Module._compile (node:internal/modules/cjs/loader:1101:14)
#8 92.22     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
#8 92.22     at Module.load (node:internal/modules/cjs/loader:981:32)
#8 92.22     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
#8 92.22   code: 'ERR_DLOPEN_FAILED'
#8 92.22 }
```

**Comment by JonasBa** [comment]
@Himiath thanks for the report. Does the failure happen when you are running yarn install? If so, would it be possible for you to switch to npm just to test and give us the output of the following command? `npm install --verbose --foreground-scripts @sentry/profiling-node`?

I have just tested the code you shared on docker app and it worked without any issues

**Comment by JonasBa** [comment]
@Himiath I think this might be related to the issue described here - https://github.com/microsoft/vscode/issues/178748
Would you mind trying to use node 16.20-alpine docker image?

**Comment by Himiath** [comment]
I have tried the 16.20-alpine image and it worked a charm. Currently over our ratelimit so can't verify in the dashboard but I see one dropped profile on my account so looks like it is working with this deployed to our dev environment as well!
