### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by JonasBa** [getsentry/profiling-node#139]
## Profiling source map support
> _keeping this public for future references or others looking to implement profiling sourcemap support. This is considered a work in progress document_

The current state of Sentry node and browser profiling currently does not support sourcemaps, this is mostly a problem in browser profiling where most of the time code is minified. In Node.js, this is less often the case, but can be common in lambda environments where bundling and modification is done in order to improve cold starts. 

The tldr is that not supporting sourcemaps makes profiles unusable as frame names are mangled.
<img width="454" alt="CleanShot 2023-04-27 at 09 42 23@2x" src="https://user-images.githubusercontent.com/9317857/234880628-2809c428-9555-498d-925b-36e640839535.png">

**Current (errors SDK) behavior:** 
- Sentry Webpack plugin injects a pathname/sourcemap dict stored as a global variable into runtime

```
 /**
   * Debug IDs are indirectly injected by Sentry CLI or bundler plugins to directly reference a particular source map
   * for resolving of a source file. The injected code will place an entry into the record for each loaded bundle/JS
   * file.
   */
  _sentryDebugIds?: Record<string, string>;

^^ is stored as InternalGlobal, but is publicly available
```
- Errors SDK [parses the current error stacktrace](https://github.com/getsentry/sentry-javascript/blob/fa40976e35b06fb60e04ed66d0a974afeb1509b5/packages/core/src/utils/prepareEvent.ts#L126) and [only sends the sourcemaps relative to each error](https://github.com/getsentry/sentry-javascript/blob/fa40976e35b06fb60e04ed66d0a974afeb1509b5/packages/core/src/utils/prepareEvent.ts#L41-L44). Profiling requirements are of the same nature, but differ in magnitude as we need sourcemaps for each of the frames in n number of stacks to be reported. The concern of sending that many files is network and CPU overhead so this should be evaluated carefully. Having stats on sourcemap files across sentry projects would help so we can roughly evaluate what we are dealing with in production.

**Considerations:**
- The CLI plugin [recommendation](https://github.com/getsentry/sentry-webpack-plugin#usage) is to ignore node_modules. I need to validate what that means in practice, e.g. what happens when we have a `vendors.bundle.js`, does it contain the sourcemap reference?

<img width="740" alt="CleanShot 2023-04-27 at 09 44 50@2x" src="https://user-images.githubusercontent.com/9317857/234881393-02808299-122b-4fca-9276-7d78d811d78d.png">

- If required, the impact of removing the node_modules ignore flag in our CLI plugin needs to be evaluated

**Next steps:**
- Create a repo with build step + sentry cli plugin that can execute minified source code where
- Profile some code from a package dependency and check the impact of ignoring node_modules

Notes:
- add docs on how to build with aws serverless and mark profiling-node as external lib
- eval if we want to hardcode list of binaries in SDK so they can be properly moved by bundlers

**Comment by JonasBa** [comment]
A prerequisite to making bundling work is to ensure binaries are not bundled by default (see dynamicRequire in our @sentry/node SDK). Need to figure out how to escape that while still supporting esm and cjs

**Comment by JonasBa** [comment]
After a bit of digging, it seems that my resolve problem boils down to webpack attempting to evaluate n(6263)(e) which 
```ts
const _require = require; // for esm we transpile this to _require = createRequire(import.meta.url);
function dynamicRequire<T>(module: NodeJS.Module, request: string): T {
  return module && module.require ? module.require(request) : _require(request);
}
// becomes
function h(t, e) {
  return t && t.require ? t.require(e) : n(6263)(e); // where n(6263)(e) throws a missing module error (require is never called)
}
```

**Comment by lforst** [comment]
> Errors SDK [parses the current error stacktrace](https://github.com/getsentry/sentry-javascript/blob/fa40976e35b06fb60e04ed66d0a974afeb1509b5/packages/core/src/utils/prepareEvent.ts#L126) and [only sends the sourcemaps relative to each error](https://github.com/getsentry/sentry-javascript/blob/fa40976e35b06fb60e04ed66d0a974afeb1509b5/packages/core/src/utils/prepareEvent.ts#L41-L44). Profiling requirements are of the same nature, but differ in magnitude as we need sourcemaps for each of the frames in n number of stacks to be reported.

Just wanna say that the SDK does not send source maps (especially not files). It just sends IDs that reference the source maps which have been uploaded to the Sentry backend before. It does not even scale per frame. It scales _per file_ and only per file that is part of a stack trace (or profile I guess).

**Comment by lforst** [comment]
Honestly I would just bundle the `@sentry/profiling-node` package as part of publishing it (e.g. with rollup). That way people can just safely mark it as external without having all the slow require calls.

**Comment by JonasBa** [comment]
@lforst yeah, that makes sense - I wasnt precise enough in my issue, I meant sourcemap ids. I need to see exactly how all that works, for now I just wanted to setup an env where I can send start testing and seeing how it all fits together.

My concern is that we will likely need debug metadata for dependencies else profiles are not going to be very useful.

For bundling - that makes sense. I'll make that change.

**Comment by lforst** [comment]
> For bundling - that makes sense. I'll make that change.

Nice!

> My concern is that we will likely need debug metadata for dependencies else profiles are not going to be very useful.

@JonasBa Debug IDs / debug metadata will generally already also work for dependencies. For browser or bundled node, the only thing that needs to happen is that users need to bundle their deps with sourcemaps. If they're on unbundled node and directly require deps from node_modules, that's a different story but I have ideas. We could tell users to upload their node_modules and Symbolicator should be smart enough to resolve the source.

**Comment by JonasBa** [comment]
@lforst yeah, that's what I anticipated. For uploading dependency sourcemaps, is that is controlled by the SentryWebpackPlugin ignore option? We would just need to ask folks to update that to include node_modules, but seems fairly straightforward otherwise

**Comment by JonasBa** [comment]
Implemented in https://github.com/getsentry/profiling-node/pull/144, thanks @lforst for the review
