### ISSUE TITLE
`esbuild.serverless.js` seems misleading/wrong

### ISSUE THREAD

**Issue by oliversalzburg** [getsentry/profiling-node#157]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### SDK Version

0.3.0

### What environment is your node script running in?

AWS Lambda

### Are you using an alpine based docker image?

- [ ] Yes (please specify the version)
- [X] No (please describe your environment)

### Does the failure occur on a remote environment only?

- [ ] Yes (please describe your environment)
- [X] No (please describe your local environment)

### If you are using alpine, have you tried using latest version of alpine or (currently alpine3.16 or alpine3.17)?

- [ ] Yes (please specify the version)"
- [X] No, and I cannot upgrade

### Have you tried using the latest minor version of node (currently 16.20 or 18.15)?

- [X] Yes 20.1.0
- [ ] No, and I cannot upgrade

### If you run npm install --verbose --foreground-scripts @sentry/profiling-node in an empty directory, what is the output?

[install.log](https://github.com/getsentry/profiling-node/files/11635378/install.log)

### Actual Issue Report

The example in the `README` suggests to use `outfile: "./dist",` in the esbuild configuration, which is an invalid setting for `outfile`.

When using the correct `outdir` instead, there are still no `.node` files being copied at all, resulting in MODULE_NOT_FOUND errors down the line.

**Comment by JonasBa** [comment]
@oliversalzburg The .node file is not there yet because we still need to release a new version that enable the changes. I'll look into validity of the esbuild config file

**Comment by oliversalzburg** [comment]
Oh, that explains it then :D Should I try the alpha instead? Or did I miss anything else about how to make the 0.3.0 work with bundling?

**Comment by JonasBa** [comment]
@oliversalzburg I am targeting to release 1.0.0 today by eod so I would say best to wait :)

**Comment by JonasBa** [comment]
@oliversalzburg I just tested beta-1 with esbuild ^0.17.18 with the following config and I can see all the binary files moved. Do you mind 

```
const { sentryEsbuildPlugin } = require("@sentry/esbuild-plugin");

require("esbuild").build({
  entryPoints: ["./index.cjs"],
  outfile: "./dist/esbuild-serverless/index.cjs",
  platform: "node",
  format: "cjs",
  bundle: true,
  minify: true,
  sourcemap: true,
  loader: {
    '.node': 'copy',
  },
  plugins: [
    // Put the Sentry esbuild plugin after all other plugins
    sentryEsbuildPlugin({
      project: "",
      org: "",
      authToken: "",
      release: process.env.SENTRY_RELEASE,
      sourcemaps: {
        // Specify the directory containing build artifacts
        assets: "./dist/**",
      },
    }),
  ],
});
```

<img width="439" alt="CleanShot 2023-06-05 at 10 52 41@2x" src="https://github.com/getsentry/profiling-node/assets/9317857/5b626564-9072-42a9-8044-fbd58b4f9cef">

Would you mind testing with the same config as I am using to see if it works for you? If it doesn't, then I would proceed by enabling the other options to see if any of them break the binary copy procedure

**Comment by oliversalzburg** [comment]
I have esbuild 0.17.19 over here. It's still not behaving as it should with your config. I'll try to find out what's special on my side :(

**Comment by JonasBa** [comment]
That is unfortunate and I do not quite understand the reasoning behind that. I think the best next step would be to mark @sentry/profiling-node as an external package and opening an issue on esbuild repository regarding the copying of binaries.

**Comment by JonasBa** [comment]
Yeah, @oliversalzburg if you mark the package as external, then you need to also ensure it's installed - I think someone else had this problem [here](https://github.com/getsentry/profiling-node/issues/141#issuecomment-1536465408) and they managed to make it work. It's a shame .mts does not end up copying files which would make this work out the box. 

An alternative that maybe is not the most pretty, but will work is to not mark the package as external and copy the binaries yourself. Something like `cp node_modules/@sentry/profiling-node/lib/binaries/*.node ./dist` should make the binaries available and fix the missing module error

**Comment by adesso-os** [comment]
After the most recent feedback, I think I will just have to find a way to copy the binaries manually. Very interesting insights though.

I just really wanted to avoid the manual copy, because it feels so fragile. Maybe paths change in the future, or the location of packages changes in the monorepo. I'd just feel better if it was fully automated through bundling :D

**Comment by adesso-os** [comment]
After deploying this, I see new problems. My deployed code will fail on the `createRequire` call. I assume it's because `import.meta.url` doesn't exist in the resulting CJS context.

I saw your latest comment on the esbuild thread. If you're going to make any adjustments to the plugin, I'd be happy to give those a test-drive :)

**Comment by JonasBa** [comment]
Yes @adesso-os, I made some changes and will release beta.2 soon that hopefully fixes this

**Comment by adesso-os** [comment]
That seems to be working beautifully :) esbuild also now specifically complains if I don't specify a loader for the `.node` files. Thanks for the quick solution!

**Comment by JonasBa** [comment]
Perfect, sorry for the back and forth, hope you enjoy using profiling!

**Comment by JonasBa** [comment]
@adesso-os worth noting that I will release a first major version in the next day or so. Feel free to upgrade to that

**Comment by oliversalzburg** [comment]
I feel like something might still be off, but I will create a new ticket for it when I'm back to work. I'm now seeing new runtime errors (`Error: Dynamic require of "child_process" is not supported`) and I see that there is a bunch of CJS code in the plugin, even though I thought it should pick the ESM versions of its dependencies for the bundle.

![image](https://github.com/getsentry/profiling-node/assets/1658949/d4ca82dd-d696-422f-b5df-2260510084a4)

**Comment by oliversalzburg** [comment]
The stack trace is:
```
  1) Uncaught error outside test suite:
     Uncaught Error: Dynamic require of "child_process" is not supported
      at file:///home/runner/work/dcc-backend/dcc-backend/node_modules/@sentry/profiling-node/lib/index.mjs:12:9
      at node_modules/detect-libc/lib/detect-libc.js (file:///home/runner/work/dcc-backend/dcc-backend/node_modules/@sentry/profiling-node/lib/index.mjs:9512:24)
      at __require2 (file:///home/runner/work/dcc-backend/dcc-backend/node_modules/@sentry/profiling-node/lib/index.mjs:15:50)
      at file:///home/runner/work/dcc-backend/dcc-backend/node_modules/@sentry/profiling-node/lib/index.mjs:16572:34
      at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
```

I looked at that, and the line in question seems to be an import in `node_modules/detect-libc/lib/detect-libc.js`. It looked like that is a result of the cjs variants of other @sentry modules being used.

In the bundle of of the profiling-node plugin, there are these suspicious imports:
```
// src/hubextensions.ts
var import_utils3 = __toESM(require_cjs());
var import_core = __toESM(require_cjs2());
```

Not sure why it would first wrap the CJS of @sentry/utils and @sentry/node, and then try to convert that back to ESM, when those modules already provide ESM exports. I also looked at the `package.json` of those modules, but couldn't make sense of it. :(

Hope you have more luck.

**Comment by oliversalzburg** [comment]
With 1.0.2 I'm back to missing the `.node` files in the build output (looks like it's using `require` again), and there still seems to be CJS code from dependencies in the bundle too (like `node_modules/@sentry/utils/cjs/worldwide.js`) :(

**Comment by oliversalzburg** [comment]
@JonasBa Basically only results in other build errors:
```
✘ [ERROR] Could not resolve "@sentry/profiling-node/lib/index.js"

    ../packages/lib-lambda/output/sentry/SentryIntegration.mjs:2:37:
      2 │ import { ProfilingIntegration } from "@sentry/profiling-node/lib/index.js";
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./lib/index.js" is not exported by package "@sentry/profiling-node":

    ../node_modules/@sentry/profiling-node/package.json:12:13:
      12 │   "exports": {
         ╵              ^

  You can mark the path "@sentry/profiling-node/lib/index.js" as external to exclude it from the
  bundle, which will remove this error.
```

**Comment by oliversalzburg** [comment]
So I'm looking at the `index.js` and `index.mjs` of the 1.0.3, and the code in the bundle pretty early contains `// node_modules/@sentry/utils/cjs/is.js` for both bundles. I wonder if this already points at a larger issue. 

As `@sentry/utils` has ESM content, I would expect to see that in the bundle as well, right?

**Comment by oliversalzburg** [comment]
I also tried going back to CJS bundle, just to see if that works, but that also leads to new errors:
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".node" for /home/runner/work/dcc-backend/dcc-backend/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-x64-glibc-108.node
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
```

When I'm building a CJS bundle, I don't understand why it will contain parts of the plugin code that uses `import`, but I don't even understand if that's the issue here.

Either way, I'll probably have to give up on Sentry profiling now, as this was supposed to be a quick task and I'm way over budget. Thanks for the efforts.

**Comment by adesso-os** [comment]
I will likely come back to this at a later time, but the way our Lambda bundling/deployment works right now, setting things as external is not a full solution for us.

In general, we don't necessarily want to use ESM for the bundle, but the CJS approach also didn't work for us initially. We'll definitely come back to this, I just can't invest any more right now. Your efforts are appreciated nonetheless :)

**Comment by adesso-os** [comment]
Just FYI, with the latest release, I was also able to make profiling work on our project. I noticed something interesting though. I build all our lambdas in a single process. I just provide all the entrypoints and let esbuild write the output directory structure. 

In that scenario, the `.node` files are only copied once to the root of the output directory, and the import statements will then reference that file with `../../../..` relative paths.

I resolved that with the plugin below, which also copies the file to the output root, but rewrites the import to be `./`. Then I can copy the `.node` file into the root of the individual lambda output folder when the build completes.

```ts
// We want the profiling binary to reside at the root of each lambda folder.
// We ensure manually that the right plugin is bundled together with each lambda.
// This plugin ensures that the import paths in the build output refer to the
// correct locations.
const sentryProfilingImportPathPlugin = {
  name: "SentryProfilingImportPath",
  setup(build) {
    build.onResolve({ filter: /sentry_cpu_profiler.+\.node$/ }, async resolveArgs => {
      fs.mkdirSync(pathOutput, {
        recursive: true,
      });
      fs.copyFileSync(
        path.resolve(resolveArgs.resolveDir, resolveArgs.path),
        path.resolve(pathOutput, resolveArgs.path)
      );
      return { path: resolveArgs.path, external: true };
    });
  },
};
```

And then copying to all output directories at the end of the build:

```ts
// Try finding the right Sentry profiling plugin for our arch.
    const profilingPlugins = fs
      .readdirSync(pathOutput)
      .filter(file => file.match(/sentry_cpu_profiler/));
    const profilingPlugin = profilingPlugins.filter(file => file.match(new RegExp(arch)))[0];
    if (!profilingPlugin) {
      console.warn(
        `Cannot find matching Sentry profiling plugin for '${arch}'! Sentry profiling will not work in this build!`
      );
    } else {
      // Copy the plugin to all output directories.
      console.info(
        `Found '${profilingPlugins.length}' Sentry profiling plugin candidates in build output. Desired architecture is '${arch}'.`
      );
      console.info(
        ` + Choosing: '${profilingPlugin}' and associating with '${lambdaEntrypoints.length}' lambda outputs...`
      );
      for (const lambdaMain of lambdaEntrypoints) {
        fs.copyFileSync(
          path.resolve(pathOutput, profilingPlugin),
          path.resolve(path.dirname(lambdaMain.path), profilingPlugin)
        );
      }
    }
```

Maybe this helps someone else :)
