### ISSUE TITLE
Next.js using profiling-node on latest version (1.0.4) of this package

### ISSUE THREAD

**Issue by dkryptr** [getsentry/profiling-node#164]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

1.0.4

### What environment is your node script running in?

Next.js

### How is your code deployed and bundled?

Deploying using Vercel. Next.js as the bundler.

### Steps to Reproduce

1. Create a Next.js project from scratch
2. Implement Next.js Sentry integration based on documentation
3. Implement the new profiling feature for Next.js in the `sentry.server.config.js` file
4. Start the dev server

I haven't tested these steps to reproduce, but I assume the same issue will occur.

### Expected Result

Next.js runs local development environment

### Actual Result

Next.js local dev run errors out.

![Screenshot 2023-06-13 171809](https://github.com/getsentry/profiling-node/assets/13036301/218faede-27f3-4c57-a689-66b8b377cf0d)

**Comment by sshah98** [comment]
got the same thing

**Comment by dkryptr** [comment]
@JonasBa Bringing this to your attention.

**Comment by JonasBa** [comment]
@dkryptr this seems to be yet another breaking change in esm behavior which fails at recognizing .node files (cjs does and everything work fine)

I will likely fully remove esm support as it has been only a headache so far, as a workaround, can you tell me if importing the CJS build via `import {ProfilingIntegration} from "@sentry/profiling-node/lib/index.js"` works?
