### ISSUE TITLE
v1.0.4 TypeError PrivateCpuProfilerBindings.startProfiling is not a function

### ISSUE THREAD

**Issue by lhermann** [getsentry/profiling-node#165]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

1.0.4

### Link to Sentry event

https://lhdev.sentry.io/share/issue/1072ba69a582461cb3ce29efa167a2e1/

### What environment is your node script running in?

Docker container `node:16-alpine` with vanilla JS and express.

### How is your code deployed and bundled?

It's vanilla javascript code using ES6 import and `"type": "module"` without any additional bundling or build steps.

### Steps to Reproduce

1. Include the profiling integration.

```js
import { ProfilingIntegration } from '@sentry/profiling-node'

Sentry.init({
  ...
  integrations: [
    new ProfilingIntegration(),
  ],
  profilesSampleRate: 0.2,
})
```

2. Add as express middleware:
```js
const app = express()
app.use(Sentry.Handlers.requestHandler())
app.use(Sentry.Handlers.tracingHandler())
// other middleware and routes
app.use(Sentry.Handlers.errorHandler())
...
```

3. Make a request that the profiler decides to sample.
4. Get 500 error response.
5. Downgrade to v0.3.0 and it works as expected.

### Expected Result

Request returns desired response (2xx, 3xx, 4xx)

### Actual Result

Request returns 500. Server throws error:

```
TypeError: PrivateCpuProfilerBindings.startProfiling is not a function
  File "/home/node/app/node_modules/@sentry/profiling-node/lib/index.mjs", line 16701, col 39, in Object.startProfiling
    return PrivateCpuProfilerBindings.startProfiling(name);
... (see sentry link)
```

**Comment by JonasBa** [comment]
@lhermann the module loading is no longer async, this should not happen anymore. Let us know if it does, I'm closing the issue for now.
