### ISSUE TITLE
esbuild error with this package

### ISSUE THREAD

**Issue by mattmbrightside** [getsentry/profiling-node#189]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

7.61.1

### What environment is your node script running in?

aws lambda node16.x

### How is your code deployed and bundled?

esbuild

### Steps to Reproduce

lambda includes sentry dependencies
	"dependencies": {
		"@sentry/node": "^7.61.1",
		"@sentry/profiling-node": "^1.1.2",
		"@sentry/serverless": "^7.61.1"
	}

we run npm install then esbuild using the AWS SAM cloudformation setup as follows
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.js

### Expected Result

a bundle is produced that I can deploy to AWS cloud

### Actual Result

Build fails with:
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: ✘ [ERROR] No loader is configured for ".node" files: node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-darwin-x64-83.node

This is probably the same issue as https://github.com/getsentry/profiling-node/issues/170 but since that was for Next.js and this is for esbuild I didnt want to cause any confusion.

**Comment by JonasBa** [comment]
esbuild doesn't know how to process a .node file, you need to configure the appropriate loader. The copy loader will ensure the binary is copied to your dist and it's path is properly referenced.

```
loader: {
    // ensures .node binaries are copied to ./dist
    '.node': 'copy',
  },
```

Let me know if that doesn't work, there is a full bundling how-to in the [readme.md](https://github.com/getsentry/profiling-node#bundling)
