### ISSUE TITLE
Version collision with @sentry/profiling-node and other Sentry packages

### ISSUE THREAD

**Issue by cietho** [getsentry/profiling-node#195]
When updating **@sentry/profiling-node** to the latest version via Renovate, we noticed that it uses a different versioning style for its dependencies. More specifically, it uses the SemVer range specifier (`^`), e.g. `^7.66.0`. This is in contrast to other **@sentry** packages which pin their dependencies, e.g. `7.66.0`. And that seems to lead to TypeScript errors when building.

**Environment**
- Local environment running the current Node LTS

**Logs**
```
Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.
Type 'ProfilingIntegration' is not assignable to type 'Integration'.
```

**Suggested Solution**
The versioning for **@sentry/profiling-node** could match the other **@sentry** packages by pinning its dependencies. This change would help avoid TypeScript errors and make sure all packages work well together.

**Comment by kevin-riou-technis** [comment]
I totally agree, it could be very nice

**Comment by JonasBa** [comment]
I will pin these, but the real change will be for us to move this repo over to sentry-javascript so we can more seemingly keep up with the updates.

**Comment by mydea** [comment]
IMHO not sure if pinning this will actually help, as that just means you _have_ to keep your `node-profiling` and core sentry packages versions in sync, just leading to potentially other issues? I think `^` is better, then in the host app you _can_ still update your core Sentry package (you just need to make sure to dedupe your dependencies)...?

**Comment by dargmuesli** [comment]
This package is now part of sentry-javascript, right, @JonasBa? Therefore this issue can be marked as resolved, I think.

**Comment by JonasBa** [comment]
@dargmuesli correct, let me close this. Thank you for noticing this!
