### ISSUE TITLE
sentry_cpu_profiler-linux-arm64-glibc-120.node does not exist

### ISSUE THREAD

**Issue by andrewpile** [getsentry/profiling-node#212]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

1.2.6

### What environment is your node script running in?

 - NodeJS app running inside Docker `node:21-slim`
 - Host is M1 MacBook Pro

### How is your code deployed and bundled?

Bundled with esbuild

### Steps to Reproduce

I installed `@sentry/profiling-node` and included it in the codebase normally. On execution I'm seeing this error: `Error: Cannot find module '/app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-120.node'` (note the **glibc-120**).

At first I thought this was as simple as instructing esbuild to include the binary as an external since normally `.node` wouldn't be bundled, but then I saw that the **glibc-120** binary doesn't actually exist?

```
$ ls /app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-120.node
ls: cannot access '/app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-120.node': No such file or directory

$ ls /app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-*
/app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-108.node
/app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-115.node
/app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-83.node
/app/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-glibc-93.node
```

### Expected Result

Profiling library is loaded

### Actual Result

App crashes at startup

**Comment by andrewpile** [comment]
It occurs to me that this is because I'm using node v21 and that docker image must be using a different glibc? It might be worth adding supported glibc version to the docs. Closing!

**Comment by andrewpile** [comment]
I rolled back to the `node:20-slim` image and it worked!

**Comment by JonasBa** [comment]
@andrewpile we do not support non-LTS nodejs release versions and as far as I'm aware it is not advisable to use them for production systems
