### ISSUE TITLE
Preparation to move to sentry-javascript repository

### ISSUE THREAD

**Issue by anonrig** [getsentry/profiling-node#219]
TODOs

- [x] Remove prettier and related files https://github.com/getsentry/profiling-node/pull/220
- [x] Remove prettier from eslintrc as well
- [x] Have `format` and `fix` keys on `package.json` https://github.com/getsentry/profiling-node/pull/222
- [x] Update tsconfig files depending on monorepo
- [x] Remove package-lock.json since monorepo uses yarn
- [ ] Update Github workflows to use latest Ubuntu
- [x] Move jest config and tests https://github.com/getsentry/profiling-node/pull/221
- [x] Remove all eslint dependencies and sync eslintrc with monorepo

When we open PR to sentry-javascript
- [ ] drop @typescript-eslint/eslint-plugin and @typescript-eslint/parser - currently fails even though it's a dep of the SDK config package?

**Comment by JonasBa** [comment]
Afaik we had issues with prebuilding binaries on latest ubuntu, so we downgraded
