### ISSUE TITLE
Cannot find package 'node-abi' imported from 

### ISSUE THREAD

**Issue by sz-joao-pacheco** [getsentry/profiling-node#224]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### SDK Version

1.3.0

### What environment is your node script running in?

GitHub Actions:

with:
    node-version: 18
    always-auth: false
    check-latest: false
    token: ***

### Are you using an alpine based docker image?

- [ ] Yes (please specify the version)
- [ ] No (please describe your environment)

### Does the failure occur on a remote environment only?

- [ ] Yes (please describe your environment)
- [ ] No (please describe your local environment)

### If you are using alpine, have you tried using latest version of alpine or (currently alpine3.16 or alpine3.17)?

- [ ] Yes (please specify the version)"
- [X] No, and I cannot upgrade

### Have you tried using the latest minor version of node (currently 16.20 or 18.15)?

- [ ] Yes (please specify the version)
- [ ] No, and I cannot upgrade

### If you run npm install --verbose --foreground-scripts @sentry/profiling-node in an empty directory, what is the output?

Run npm i
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated bree@6.5.0: bree@7.0.0 drops support for the browser, Node <12.11.0, and removes bthreads entirely. Either upgrade to v7.0.0 or lock your bree version to v6.5.0.
npm WARN deprecated sequelize@5.22.5: Please update to v6 or higher! A migration guide can be found here: https://sequelize.org/v6/manual/upgrade-to-v6.html
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /home/runner/work/beestock_backend/beestock_backend/node_modules/@sentry/profiling-node
npm ERR! command failed
npm ERR! command sh -c node scripts/check-build.mjs
npm ERR! node:internal/errors:496
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-abi' imported from /home/runner/work/beestock_backend/beestock_backend/node_modules/@sentry/profiling-node/scripts/binaries.mjs
npm ERR!     at new NodeError (node:internal/errors:405:5)
npm ERR!     at packageResolve (node:internal/modules/esm/resolve:916:9)
npm ERR!     at moduleResolve (node:internal/modules/esm/resolve:973:20)
npm ERR!     at defaultResolve (node:internal/modules/esm/resolve:1193:11)
npm ERR!     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
npm ERR!     at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
npm ERR!     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
npm ERR!     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
npm ERR!     at link (node:internal/modules/esm/module_job:75:36) {
npm ERR!   code: 'ERR_MODULE_NOT_FOUND'
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.19.0

### Crash report

npm ERR! Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-abi' imported from /home/runner/work/beestock_backend/beestock_backend/node_modules/@sentry/profiling-node/scripts/binaries.mjs
npm ERR!     at new NodeError (node:internal/errors:405:5)
npm ERR!     at packageResolve (node:internal/modules/esm/resolve:916:9)
npm ERR!     at moduleResolve (node:internal/modules/esm/resolve:973:20)
npm ERR!     at defaultResolve (node:internal/modules/esm/resolve:1193:11)
npm ERR!     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
npm ERR!     at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
npm ERR!     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
npm ERR!     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
npm ERR!     at link (node:internal/modules/esm/module_job:75:36) {
npm ERR!   code: 'ERR_MODULE_NOT_FOUND'

**Comment by JonasBa** [comment]
@sz-joao-pacheco sorry about that. Can you upgrade to v1.3.1 and reopen the issue if it's still problematic?
