### ISSUE TITLE
@sentry/profiling-node crashes vitest 

### ISSUE THREAD

**Issue by capaj** [getsentry/profiling-node#228]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/node

### SDK Version

7.92.0

### Framework Version

vitest any

### SDK Setup

```js
import * as SentryApi from '@sentry/node';
// Edit an assertion and save to see HMR in action
import { ProfilingIntegration } from '@sentry/profiling-node';

SentryApi.init({
  integrations: [new ProfilingIntegration()],
});

```

### Steps to Reproduce

I tried to setup a minimal repro here: https://stackblitz.com/edit/vitest-dev-vitest-1gd3e9?file=src%2Fsentry.ts

but I failed, because profiling integration does not run on stackblitz. 
So what you need to do:
 1. download from stackblitz
 2. extract
 3. pnpm i
 4. pnpm test
 5. hit enter to restart the tests for few seconds(10 times probably+-)

### Expected Result

Vitest does not crash

### Actual Result

vitest crashes after a few runs
[Screencast from 5.1.2024 17:53:35.webm](https://github.com/getsentry/sentry-javascript/assets/1305378/2374622c-5a07-40f7-a0f5-b3d9d84741f6)

**Comment by JonasBa** [comment]
@capaj do I understand correctly when you say that it crashes after some random number of test restarts?

**Comment by capaj** [comment]
Yes it crashes after roughly 10 runs 

I have node 20 but it reproduces on 18 too

**Comment by JonasBa** [comment]
Yup, I managed to reproduce. I dont know for sure, but I suspect this might be related to how vitest spawns threads to run tests (I haven't looked into how vitest works yet) and we don't clean up the napi instance data correctly.

**Comment by JonasBa** [comment]
@capaj mind upgrading to 1.3.3 and testing this? I just tested the code you provided and failed to reproduce the issue.

**Comment by daniluk4000** [comment]
I still have the same error. After I have disabled profiling (on dev), errors stopped from happening. 

Errors were also followed by ECONNRESET and ECONNREFUSED in node console.
