### ISSUE TITLE
Version 1.3.4 missing type declarations

### ISSUE THREAD

**Issue by Alx101** [getsentry/profiling-node#237]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### SDK Version

1.3.4

### What environment is your node script running in?

Docker image node:20.10-slim
Typescript 4.9.5

### Are you using an alpine based docker image?

- [ ] Yes (please specify the version)
- [X] No (please describe your environment)

### Does the failure occur on a remote environment only?

- [ ] Yes (please describe your environment)
- [X] No (please describe your local environment)

### If you run npm install --verbose --foreground-scripts @sentry/profiling-node in an empty directory, what is the output?

npm verb cli /Users/alexornberg/.nvm/versions/node/v20.10.0/bin/node /Users/alexornberg/.nvm/versions/node/v20.10.0/bin/npm
npm info using npm@10.2.3
npm info using node@v20.10.0
npm verb title npm install @sentry/profiling-node
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "@sentry/profiling-node"
npm verb logfile logs-max:10 dir:/Users/alexornberg/.npm/_logs/2024-01-12T10_48_46_232Z-
npm verb logfile /Users/alexornberg/.npm/_logs/2024-01-12T10_48_46_232Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/@sentry%2fprofiling-node 1261ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/@sentry%2fnode 70ms (cache revalidated)
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-win32-x64-msvc
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-win32-ia32-msvc
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-win32-arm64-msvc
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-linux-x64-musl
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-linux-x64-gnu
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-linux-riscv64-gnu
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-linux-arm64-musl
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-linux-arm64-gnu
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-linux-arm-gnueabihf
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-darwin-x64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-android-arm64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@rollup/rollup-android-arm-eabi
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/win32-x64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/win32-ia32
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/win32-arm64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/sunos-x64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/openbsd-x64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/netbsd-x64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/linux-x64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/linux-s390x
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/linux-riscv64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/linux-ppc64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/linux-mips64el
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/linux-loong64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/linux-ia32
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/linux-arm64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/linux-arm
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/freebsd-x64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/freebsd-arm64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/darwin-x64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/android-x64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/android-arm64
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/android-arm
npm verb reify failed optional dependency /Users/alexornberg/code/jura/services/backend/node_modules/@esbuild/aix-ppc64
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 235ms
npm http fetch GET 200 https://registry.npmjs.org/axios 32ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/intercom-client 830ms (cache revalidated)

### Crash report

```
Could not find a declaration file for module '@sentry/profiling-node'. '{HOME_PATH_HERE}/node_modules/@sentry/profiling-node/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sentry__profiling-node` if it exists or add a new declaration (.d.ts) file containing `declare module '@sentry/profiling-node';` (tsserver 7016)
```

Version 1.3.3 does not have the same issue, it's only on 1.3.4 where this occurs.

**Comment by breautek** [comment]
Ran into the same issue and investigated, despite master looking right, whats installed in node_modules/ it's looking for types in `lib/index.d.ts` when the proper path is `lib/types/index.d.ts`

Looks like it was fixed in https://github.com/getsentry/profiling-node/commit/0e4827394570d9402f02b66d1b4d546c06bc0013

Just that only happened after the 1.3.4 release.

**Comment by breautek** [comment]
1.3.5 appears to work for me again, thanks for the swift hotfix.
