### ISSUE TITLE
Evaluate inspector API in Node 19

### ISSUE THREAD

**Issue by JonasBa** [getsentry/profiling-node#79]
### Problem Statement

Node 19 includes an experimental API that allows us to access the profiler, we need to evaluate if that can be used as it could mean we can get rid of our custom bindings https://nodejs.org/docs/latest-v19.x/api/inspector.html

### Solution Brainstorm

N/A

**Comment by timfish** [comment]
The non-async version has been available since v14:
https://nodejs.org/docs/latest-v14.x/api/inspector.html

I'm currently using it to add stack local variables to the node SDK as per Kamil's demo:
https://github.com/kamilogorek/sentry-node-local-variables

**Comment by JonasBa** [comment]
@timfish One thing we need to evaluate is if we can pass options to the CPU profiler (I can see we can pass the sampling interval, but not specify the logging mode). We are also doing a fair bit of processing to convert to our sampled format which happens in c++ so maybe there is some benefit to keeping the bindings.

**Comment by JonasBa** [comment]
We need to conform to our sampled format and doing the conversion in c++ allows us to sequentially iterate over the samples (which is what our format expects), the returned value from the inspector does not allow us to do that as it returns the call graph directly https://chromedevtools.github.io/devtools-protocol/v8/Profiler/#type-Profile
