### ISSUE TITLE
Informational: Profiling Overhead 800ms+ (lazy mode)

### ISSUE THREAD

**Issue by mtimbs** [getsentry/profiling-node#85]
This is an informational Issue as it is already noted in the documentation but thought I would provide some more data from an actual production system serving a decent base load of traffic.

Adding the ProfilingIntegration has added about 900ms of latency to our `/heartbeat` endpoint when sampling occurs (current rate 20%). We were expecting some overhead (100-200ms) as stated in the documentation but the actual overhead was much higher

<img width="1441" alt="Screenshot 2023-01-04 at 12 13 14 pm" src="https://user-images.githubusercontent.com/12463905/210469606-eeed217c-8711-42ce-80da-a148d8ac9af7.png">

I will try setting `SENTRY_PROFILER_LOGGING_MODE=eager` and see if that helps things.

**Comment by mtimbs** [comment]
Eager mode fixed this (total duration <10ms) . Definitely worth running in eager mode instead of lazy. Constant CPU overhead much more preferable to a 1-2s lazy initialization

**Comment by JonasBa** [comment]
@mtimbs thanks for opening this. We are evaluating the mode during alpha stages, this somewhat depends on the script use case, but I'm leaning more and more towards flipping this to eager mode as most of the use cases people profile are server use cases.

**Comment by mtimbs** [comment]
> @mtimbs thanks for opening this. We are evaluating the mode during alpha stages, this somewhat depends on the script use case, but I'm leaning more and more towards flipping this to eager mode as most of the use cases people profile are server use cases.

I think that makes sense. I should also note we have a 2s timeout configured for this endpoint so the P99 overhead may actually be way more than 2s in practice.

**Comment by JonasBa** [comment]
@mtimbs can you share a bit more information about your environment by any chance (node version etc)? Do you have any other native packages installed and how many dependencies do you have? I'm asking this because we've seen numbers that are skewed but mostly seem to correlate with the size of the codebase

**Comment by mtimbs** [comment]
It's a 7 year old monolith that's running Node 12 still. I would say it's definitely not your typical modern stack. There's still a good amount of coffeescript rolling around too. The docker image is about 2GB if that gives you an indication of how many dependencies there are. It's all managed by k8s

**Comment by JonasBa** [comment]
Ah, the node version may be related to the issue. The recommended version to use is >=14 as there were also some memory leaks related to the CPU profiler in v8 in lower versions of node.

**Comment by JonasBa** [comment]
We are switching to eager logging by default https://github.com/getsentry/profiling-node/pull/102
